[package]
name = "ccs811"
version = "0.1.0"
authors = ["Thomas Schlage <t.schlage@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.11.3"
